const SIGNS=["Aries","Taurus","Gemini","Cancer","Leo","Virgo","Libra","Scorpio","Sagittarius","Capricorn","Aquarius","Pisces"];
const PLANETS=["Sun","Moon","Mars","Mercury","Jupiter","Venus","Saturn","Rahu","Ketu"];
const STORAGE_KEY="d1d9LifePatternAnalyzer.history.v3";
const HOUSE_LABELS={1:"Self / identity",2:"Wealth / family",3:"Effort / communication",4:"Home / emotional base",5:"Intelligence / children",6:"Obstacles / health strain",7:"Marriage / partnership",8:"Transformation / vulnerability",9:"Fortune / dharma",10:"Career / karma",11:"Gains / networks",12:"Loss / foreign / retreat"};
const referenceData=[
{title:"12 Houses – Quick Reference",items:["1st house: self, body, temperament, vitality","2nd house: family, speech, stored wealth, values","3rd house: courage, effort, siblings, communication","4th house: home, peace, mother, comforts, property","5th house: intelligence, learning style, creativity, children","6th house: debt, disease, conflict, service","7th house: marriage, contracts, public interactions","8th house: shocks, vulnerability, secrecy, transformation","9th house: blessings, father, ethics, higher guidance","10th house: karma, profession, public standing","11th house: gains, fulfilment, networks","12th house: losses, sleep, foreign stay, spiritual withdrawal"]},
{title:"Accepted Planet Names",items:["Sun","Moon","Mars","Mercury","Jupiter","Venus","Saturn","Rahu","Ketu"]},
{title:"How to Enter Planets",items:["Type comma-separated names exactly, for example: Sun, Mercury","Leave the box blank when no planet is present in that house","Each planet should appear exactly once in D1 and exactly once in D9","This version does not auto-calculate charts from date, time, and place"]}
];
let lastResult=null,lastPayload=null;
document.addEventListener("DOMContentLoaded",()=>{buildLagnaOptions();buildHouseGrids();buildReferenceGuide();setupTabs();bindEvents();renderHistory();});
function buildLagnaOptions(){const d1=document.getElementById("d1Lagna"),d9=document.getElementById("d9Lagna"),opts=SIGNS.map(s=>`<option value="${s}">${s}</option>`).join("");d1.innerHTML=opts;d9.innerHTML=opts;d1.value="Aries";d9.value="Aries";}
function buildHouseGrids(){document.getElementById("d1Grid").innerHTML=renderHouseBoxes("d1");document.getElementById("d9Grid").innerHTML=renderHouseBoxes("d9");}
function renderHouseBoxes(prefix){return Array.from({length:12},(_,i)=>{const h=i+1;return `<div class="house-box"><label for="${prefix}House${h}">House ${h}</label><textarea id="${prefix}House${h}" placeholder="Example: Sun, Mercury"></textarea><div class="house-meta">${HOUSE_LABELS[h]}</div></div>`;}).join("");}
function buildReferenceGuide(){const wrap=document.getElementById("referenceGuide"),tpl=document.getElementById("accordionTemplate");wrap.innerHTML="";referenceData.forEach(section=>{const node=tpl.content.firstElementChild.cloneNode(true);node.querySelector("summary").textContent=section.title;node.querySelector(".accordion-content").innerHTML=`<ul>${section.items.map(i=>`<li>${escapeHtml(i)}</li>`).join("")}</ul>`;wrap.appendChild(node);});}
function setupTabs(){const tabs=document.querySelectorAll(".tab"),panels=document.querySelectorAll(".tab-panel");tabs.forEach(tab=>tab.addEventListener("click",()=>{tabs.forEach(t=>t.classList.remove("active"));panels.forEach(p=>p.classList.remove("active"));tab.classList.add("active");document.getElementById(tab.dataset.tab).classList.add("active");}));}
function bindEvents(){document.getElementById("analyzeBtn").addEventListener("click",analyzeCharts);document.getElementById("resetBtn").addEventListener("click",resetForm);document.getElementById("saveSessionBtn").addEventListener("click",saveCurrentSession);document.getElementById("downloadReportBtn").addEventListener("click",downloadWordReport);}
function normalizePlanetName(name){const v=String(name||"").trim().toLowerCase();const map={sun:"Sun",moon:"Moon",mars:"Mars",mercury:"Mercury",jupiter:"Jupiter",venus:"Venus",saturn:"Saturn",rahu:"Rahu",ketu:"Ketu"};return map[v]||null;}
function parseHouseInput(prefix){const houses={};for(let h=1;h<=12;h++){const raw=document.getElementById(`${prefix}House${h}`).value.trim();houses[h]=raw?[...new Set(raw.split(",").map(p=>normalizePlanetName(p)).filter(Boolean))]:[];}return houses;}
function collectPayload(){return{nativeName:document.getElementById("nativeName").value.trim()||"Untitled Native",notes:document.getElementById("notes").value.trim(),d1:{lagna:document.getElementById("d1Lagna").value,houses:parseHouseInput("d1")},d9:{lagna:document.getElementById("d9Lagna").value,houses:parseHouseInput("d9")}};}
function validatePayload(payload){const errors=[];["d1","d9"].forEach(key=>{const seen=[];for(let i=1;i<=12;i++)seen.push(...(payload[key].houses[i]||[]));PLANETS.forEach(planet=>{const c=seen.filter(p=>p===planet).length;if(c===0)errors.push(`${key.toUpperCase()}: ${planet} is missing.`);if(c>1)errors.push(`${key.toUpperCase()}: ${planet} appears more than once.`);});});return{ok:errors.length===0,errors};}
async function analyzeCharts(){const payload=collectPayload();lastPayload=payload;const validation=validatePayload(payload),box=document.getElementById("validationBox");if(!validation.ok){box.innerHTML=`<div class="bad"><strong>Validation failed.</strong></div><ul class="bullet-list">${validation.errors.map(e=>`<li>${escapeHtml(e)}</li>`).join("")}</ul>`;return;}box.innerHTML=`<div class="good"><strong>Validation passed.</strong> Sending charts for analysis...</div>`;try{const response=await fetch("/api/analyze",{method:"POST",headers:{"Content-Type":"application/json","Accept":"application/json"},body:JSON.stringify(payload)});const raw=await response.text();let result=null;try{result=raw?JSON.parse(raw):null;}catch(parseError){throw new Error(`Server did not return valid JSON. Check Cloudflare Pages Functions routing for /api/analyze. Raw response starts with: ${raw.slice(0,120) || "[empty response]"}`);}if(!response.ok||!result||!result.ok)throw new Error((result&&result.error)||`Analysis failed with HTTP ${response.status}.`);lastResult=result;renderInsights(result);document.getElementById("downloadReportBtn").disabled=false;box.innerHTML=`<div class="good"><strong>Validation passed.</strong> Analysis completed successfully.</div>`;}catch(error){box.innerHTML=`<div class="bad"><strong>Analysis failed.</strong> ${escapeHtml(error.message)}</div>`;}}
function renderInsights(result){renderQuickVerdict(result.quickVerdict);document.getElementById("summaryBox").innerHTML=`<pre>${escapeHtml(result.summary)}</pre>`;document.getElementById("directionBox").innerHTML=`<pre>${escapeHtml(result.direction)}</pre>`;renderComparisonTable(result.comparison);renderDomainCards(result.domainInsights);renderWhyBox(result.why);renderMahadasha(result.mahadashaWatch);}
function renderQuickVerdict(items){document.getElementById("quickVerdictGrid").innerHTML=items.map(item=>`<div class="verdict-card"><h3>${escapeHtml(item.factor)}</h3><div class="verdict-value">${escapeHtml(item.verdict)}</div><div class="${toneClass(item.tone)}">${escapeHtml(item.short)}</div></div>`).join("");}
function renderComparisonTable(rows){document.getElementById("comparisonTableWrap").innerHTML=`<div class="comparison-table-wrap"><table class="comparison-table"><thead><tr><th>Life Factor</th><th>D1 Reading</th><th>D9 Reading</th><th>Combined Feedback</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${escapeHtml(r.factor)}</td><td>${escapeHtml(r.d1)}</td><td>${escapeHtml(r.d9)}</td><td>${escapeHtml(r.feedback)}</td></tr>`).join("")}</tbody></table></div>`;}
function renderDomainCards(cards){document.getElementById("domainCards").innerHTML=cards.map(c=>`<div class="domain-card"><div class="domain-group-tag">${escapeHtml(c.group)}</div><div class="status-badge ${statusClass(c.status)}">${escapeHtml(c.status)}</div><h3>${escapeHtml(c.title)}</h3><p>${escapeHtml(c.insight)}</p><h4>Feedback</h4><p>${escapeHtml(c.feedback)}</p><h4>Watchpoints</h4><ul class="inline-list">${c.watchpoints.map(p=>`<li>${escapeHtml(p)}</li>`).join("")}</ul></div>`).join("");}
function renderWhyBox(items){document.getElementById("whyBox").innerHTML=`<ul class="bullet-list">${items.map(i=>`<li>${escapeHtml(i)}</li>`).join("")}</ul>`;}
function renderMahadasha(items){const box=document.getElementById("mahadashaBox");box.innerHTML=items.length?items.map(i=>`<div class="history-item"><div class="domain-group-tag">${escapeHtml(i.planet)} Mahadasha</div><div class="status-badge ${statusClass(i.status)}">${escapeHtml(i.status)}</div><h3>${escapeHtml(i.area)}</h3><p>${escapeHtml(i.reason)}</p><p><strong>Feedback:</strong> ${escapeHtml(i.feedback)}</p></div>`).join(""):`<div class="good">No major mahadasha caution signal was triggered by the current rule set.</div>`;}
function toneClass(t){return t==="good"?"good":t==="warn"?"warn":"bad";}
function statusClass(s){s=String(s||"").toLowerCase();if(["strong","stable","supportive"].includes(s))return"status-supportive";if(["mixed","moderate","developing","watch"].includes(s))return"status-watch";if(["sensitive","vulnerable","high"].includes(s))return"status-sensitive";if(["delayed"].includes(s))return"status-delayed";return"status-watch";}
function saveCurrentSession(){const payload=lastPayload||collectPayload(),result=lastResult,history=getHistory();history.unshift({id:String(Date.now()),savedAt:new Date().toISOString(),payload,result});localStorage.setItem(STORAGE_KEY,JSON.stringify(history.slice(0,30)));renderHistory();alert("Session saved to browser history.");}
function getHistory(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY)||"[]");}catch{return[];}}
function renderHistory(){const wrap=document.getElementById("historyList"),history=getHistory();if(!history.length){wrap.innerHTML=`<div class="empty-state">No saved sessions yet.</div>`;return;}wrap.innerHTML=history.map(item=>`<div class="history-item"><div class="history-row"><div><h3>${escapeHtml(item.payload.nativeName||"Untitled Native")}</h3><div class="muted">${new Date(item.savedAt).toLocaleString()}</div><div class="muted">D1 Lagna: ${escapeHtml(item.payload.d1.lagna)} | D9 Lagna: ${escapeHtml(item.payload.d9.lagna)}</div></div><div class="history-actions"><button data-load="${item.id}">Load</button><button class="danger" data-delete="${item.id}">Delete</button></div></div></div>`).join("");wrap.querySelectorAll("[data-load]").forEach(btn=>btn.addEventListener("click",()=>loadSession(btn.dataset.load)));wrap.querySelectorAll("[data-delete]").forEach(btn=>btn.addEventListener("click",()=>deleteSession(btn.dataset.delete)));}
function loadSession(id){const item=getHistory().find(x=>x.id===id);if(!item)return;document.getElementById("nativeName").value=item.payload.nativeName||"";document.getElementById("notes").value=item.payload.notes||"";document.getElementById("d1Lagna").value=item.payload.d1.lagna;document.getElementById("d9Lagna").value=item.payload.d9.lagna;for(let h=1;h<=12;h++){document.getElementById(`d1House${h}`).value=(item.payload.d1.houses[h]||[]).join(", ");document.getElementById(`d9House${h}`).value=(item.payload.d9.houses[h]||[]).join(", ");}if(item.result){lastPayload=item.payload;lastResult=item.result;renderInsights(item.result);}activateTab("inputTab");}
function deleteSession(id){localStorage.setItem(STORAGE_KEY,JSON.stringify(getHistory().filter(i=>i.id!==id)));renderHistory();}
function activateTab(tabId){document.querySelectorAll(".tab").forEach(t=>t.classList.toggle("active",t.dataset.tab===tabId));document.querySelectorAll(".tab-panel").forEach(p=>p.classList.toggle("active",p.id===tabId));}
function resetForm(){document.getElementById("nativeName").value="";document.getElementById("notes").value="";document.getElementById("d1Lagna").value="Aries";document.getElementById("d9Lagna").value="Aries";for(let h=1;h<=12;h++){document.getElementById(`d1House${h}`).value="";document.getElementById(`d9House${h}`).value="";}document.getElementById("validationBox").textContent="No validation run yet.";document.getElementById("quickVerdictGrid").innerHTML=`<div class="empty-state">Run analysis to view quick verdict.</div>`;document.getElementById("summaryBox").innerHTML="Run analysis to view summary.";document.getElementById("directionBox").innerHTML="Overall direction feedback will appear here.";document.getElementById("comparisonTableWrap").innerHTML="Comparison table will appear here.";document.getElementById("domainCards").innerHTML="";document.getElementById("whyBox").innerHTML="Triggered rules will appear here.";document.getElementById("mahadashaBox").innerHTML="Run analysis to view mahadasha watch signals.";document.getElementById("downloadReportBtn").disabled=true;lastResult=null;lastPayload=null;}
function downloadWordReport(){if(!lastResult||!lastPayload)return;const html=`<html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:w="urn:schemas-microsoft-com:office:word" xmlns="http://www.w3.org/TR/REC-html40"><head><meta charset="utf-8"><title>D1–D9 Report</title><style>body{font-family:Arial,sans-serif;color:#111;line-height:1.45;}h1,h2,h3{color:#111;}table{border-collapse:collapse;width:100%;margin:10px 0 18px;}th,td{border:1px solid #999;padding:8px;text-align:left;vertical-align:top;}ul{margin-top:6px;}</style></head><body><h1>D1–D9 Life Pattern Analyzer Report</h1><p><strong>Native Name:</strong> ${escapeHtml(lastPayload.nativeName)}</p><p><strong>Notes:</strong> ${escapeHtml(lastPayload.notes||"-")}</p><p><strong>D1 Lagna:</strong> ${escapeHtml(lastPayload.d1.lagna)} | <strong>D9 Lagna:</strong> ${escapeHtml(lastPayload.d9.lagna)}</p><h2>Summary</h2><p>${escapeHtml(lastResult.summary)}</p><h2>Overall Direction</h2><p>${escapeHtml(lastResult.direction)}</p><h2>Quick Verdict</h2><ul>${lastResult.quickVerdict.map(v=>`<li><strong>${escapeHtml(v.factor)}:</strong> ${escapeHtml(v.verdict)} — ${escapeHtml(v.short)}</li>`).join("")}</ul><h2>D1–D9 Comparison</h2><table><thead><tr><th>Life Factor</th><th>D1 Reading</th><th>D9 Reading</th><th>Combined Feedback</th></tr></thead><tbody>${lastResult.comparison.map(r=>`<tr><td>${escapeHtml(r.factor)}</td><td>${escapeHtml(r.d1)}</td><td>${escapeHtml(r.d9)}</td><td>${escapeHtml(r.feedback)}</td></tr>`).join("")}</tbody></table><h2>Life Factor Insights</h2>${lastResult.domainInsights.map(c=>`<h3>${escapeHtml(c.title)} (${escapeHtml(c.status)})</h3><p><strong>Insight:</strong> ${escapeHtml(c.insight)}</p><p><strong>Feedback:</strong> ${escapeHtml(c.feedback)}</p><ul>${c.watchpoints.map(p=>`<li>${escapeHtml(p)}</li>`).join("")}</ul>`).join("")}<h2>Why This Conclusion</h2><ul>${lastResult.why.map(i=>`<li>${escapeHtml(i)}</li>`).join("")}</ul><h2>Mahadasha Watch Zone</h2>${lastResult.mahadashaWatch.length?lastResult.mahadashaWatch.map(i=>`<p><strong>${escapeHtml(i.planet)} Mahadasha:</strong> ${escapeHtml(i.area)} — ${escapeHtml(i.reason)} — ${escapeHtml(i.feedback)}</p>`).join(""):"<p>No major mahadasha caution signal was triggered by the current rule set.</p>"}</body></html>`;const blob=new Blob(["\ufeff",html],{type:"application/msword"}),url=URL.createObjectURL(blob),a=document.createElement("a"),safe=(lastPayload.nativeName||"d1-d9-report").replace(/[^a-z0-9]+/gi,"-").replace(/^-|-$/g,"");a.href=url;a.download=`${safe||"d1-d9-report"}.doc`;document.body.appendChild(a);a.click();document.body.removeChild(a);URL.revokeObjectURL(url);}
function escapeHtml(v){return String(v??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#39;");}